services:

  app:
    build: .
    container_name: ml_app
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  trainer:
    build: .
    container_name: trainer
    command: python main.py
    volumes:
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    volumes:
      - ./mlflow:/mlflow